// ================================================================
// lib/roomsData.js
// Modifica qui i dati di ogni camera (testi, foto, prezzi, servizi)
// ================================================================

export const rooms = [
  {
    slug: 'standard',
    name: 'Camera Matrimoniale',
    tagline: 'Il comfort essenziale del Piemonte autentico',
    description: `La Camera Matrimoniale è il punto di partenza perfetto per scoprire le Langhe. Arredata con cura artigianale, unisce funzionalità e calore in un ambiente accogliente che profuma di territorio.

Ogni dettaglio è pensato per farti sentire a casa: dalla biancheria pregiata ai prodotti da bagno locali, dalla vista sul giardino alla luce morbida del mattino piemontese.`,
    heroImg: '/foto/suite.webp',
    gallery: [
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
    ],
    price: 120,
    priceNote: 'per notte (esclusa colazione)',
    specs: [
      { icon: 'fa-bed', label: 'Predisposizione letto', value: 'Su richiesta' },
      { icon: 'fa-users', label: 'Ospiti', value: '2 Adulti' },
      { icon: 'fa-glass-whiskey', label: 'Frigobar', value: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Fumo', value: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Colazione', value: 'Inclusa' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi su richiesta' },
      { icon: 'fa-door-open', label: 'Check-in', value: 'Dalle 15:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bagno': { icon: 'fa-bath', items: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'Servizi generali': { icon: 'fa-concierge-bell', items: ['Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Servizi business': { icon: 'fa-briefcase', items: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Spazi all\'aperto': { icon: 'fa-tree', items: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'Servizi in camera': { icon: 'fa-concierge-bell', items: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media e tecnologia': { icon: 'fa-tv', items: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Servizi di ristorazione': { icon: 'fa-coffee', items: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', items: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parcheggio': { icon: 'fa-parking', items: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Servizi di accoglienza': { icon: 'fa-bell', items: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Intrattenimento famiglie': { icon: 'fa-child', items: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Servizi di pulizia': { icon: 'fa-broom', items: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Animali': { icon: 'fa-paw', items: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Attività': { icon: 'fa-bicycle', items: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibilità': { icon: 'fa-wheelchair', items: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Lingue parlate': { icon: 'fa-language', items: ['Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', value: 'Dalle 15:00 alle 22:30 — Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellazione', value: 'Gratuita fino a 48h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi su richiesta con supplemento di €15 al giorno' },
      { icon: 'fa-child', label: 'Bambini', value: 'Bambini dai 6 anni in su pagano tariffa adulti' },
      { icon: 'fa-credit-card', label: 'Metodi di pagamento', value: 'Mastercard, Visa, Maestro, Contanti' },
    ],
    surroundings: {
      'Ristoranti e Caffetterie': { icon: 'fa-utensils', items: ['Caffetteria/Bar Vino e Bottega — 1 km', 'Ristorante Da Maddalena — 1,2 km', 'Pasticceria Austa — 1,4 km'] },
      'Mezzi Pubblici': { icon: 'fa-train', items: ['Treno Costigliole d\'Asti — 5 km', 'Treno Vigliano d\'Asti — 7 km'] },
      'Aeroporti': { icon: 'fa-plane', items: ['Aeroporto di Cuneo - Levaldigi — 62 km', 'Aeroporto di Torino — 73 km', 'Aeroporto di Genova-Sestri — 93 km'] },
    },
    prev: 'singola',
    next: 'tripla',
  },
  {
    slug: 'tripla',
    name: 'Camera Tripla',
    tagline: 'Spazio e stile per chi viaggia in tre',
    description: `La Camera Tripla è pensata per chi viaggia con un amico o figlio adolescente, senza dover rinunciare a nulla. Tre letti, un ambiente armonioso e tutto il comfort della tradizione piemontese.

Spaziosa e funzionale, con possibilità di configurazione flessibile, è la soluzione ideale per condividere l'esperienza delle Langhe mantenendo comfort e privacy.`,
    heroImg: '/foto/Camera-tripla.webp',
    gallery: [
      '/foto/Camera-tripla.webp',
      '/foto/Camera-tripla.webp',
      '/foto/Camera-tripla.webp',
      '/foto/Camera-tripla.webp',
      '/foto/Camera-tripla.webp',
    ],
    price: 150,
    priceNote: 'per notte (esclusa colazione)',
    specs: [
      { icon: 'fa-bed', label: 'Predisposizione letto', value: 'Su richiesta' },
      { icon: 'fa-users', label: 'Ospiti', value: '3 Adulti' },
      { icon: 'fa-glass-whiskey', label: 'Frigobar', value: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Fumo', value: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Colazione', value: 'Inclusa' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi su richiesta' },
      { icon: 'fa-door-open', label: 'Check-in', value: 'Dalle 15:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bagno': { icon: 'fa-bath', items: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'Servizi generali': { icon: 'fa-concierge-bell', items: ['Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Servizi business': { icon: 'fa-briefcase', items: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Spazi all\'aperto': { icon: 'fa-tree', items: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'Servizi in camera': { icon: 'fa-concierge-bell', items: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media e tecnologia': { icon: 'fa-tv', items: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Servizi di ristorazione': { icon: 'fa-coffee', items: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', items: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parcheggio': { icon: 'fa-parking', items: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Servizi di accoglienza': { icon: 'fa-bell', items: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Intrattenimento famiglie': { icon: 'fa-child', items: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Servizi di pulizia': { icon: 'fa-broom', items: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Animali': { icon: 'fa-paw', items: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Attività': { icon: 'fa-bicycle', items: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibilità': { icon: 'fa-wheelchair', items: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Lingue parlate': { icon: 'fa-language', items: ['Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', value: 'Dalle 15:00 alle 22:30 — Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellazione', value: 'Gratuita fino a 48h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi su richiesta con supplemento di €15 al giorno' },
      { icon: 'fa-child', label: 'Bambini', value: 'Bambini dai 6 anni in su pagano tariffa adulti' },
      { icon: 'fa-credit-card', label: 'Metodi di pagamento', value: 'Mastercard, Visa, Maestro, Contanti' },
    ],
    surroundings: {
      'Ristoranti e Caffetterie': { icon: 'fa-utensils', items: ['Caffetteria/Bar Vino e Bottega — 1 km', 'Ristorante Da Maddalena — 1,2 km', 'Pasticceria Austa — 1,4 km'] },
      'Mezzi Pubblici': { icon: 'fa-train', items: ['Treno Costigliole d\'Asti — 5 km', 'Treno Vigliano d\'Asti — 7 km'] },
      'Aeroporti': { icon: 'fa-plane', items: ['Aeroporto di Cuneo - Levaldigi — 62 km', 'Aeroporto di Torino — 73 km', 'Aeroporto di Genova-Sestri — 93 km'] },
    },
    prev: 'standard',
    next: 'quadrupla',
  },
  {
    slug: 'quadrupla',
    name: 'Camera Quadrupla',
    tagline: 'Quattro ospiti, un\'unica esperienza indimenticabile',
    description: `La Camera Quadrupla è la scelta perfetta per gruppi di amici o famiglie che vogliono condividere gli spazi senza rinunciare al comfort individuale. Quattro posti letto in un ambiente elegante e ben organizzato.

Ideale per chi viaggia con colleghi, parenti o amici e vuole vivere le Langhe insieme, mantenendo la qualità e il calore tipici del nostro hotel.`,
    heroImg: '/foto/quadrupla.webp',
    gallery: [
      '/foto/quadrupla.webp',
      '/foto/quadrupla.webp',
      '/foto/quadrupla.webp',
      '/foto/quadrupla.webp',
      '/foto/quadrupla.webp',
    ],
    price: 200,
    priceNote: 'per notte (colazione esclusa)',
    specs: [
      { icon: 'fa-bed', label: 'Predisposizione letto', value: 'Su richiesta' },
      { icon: 'fa-users', label: 'Ospiti', value: '4 Adulti' },
      { icon: 'fa-glass-whiskey', label: 'Frigobar', value: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Fumo', value: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Colazione', value: 'Inclusa' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi su richiesta' },
      { icon: 'fa-door-open', label: 'Check-in', value: 'Dalle 15:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bagno': { icon: 'fa-bath', items: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'Servizi generali': { icon: 'fa-concierge-bell', items: ['Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Servizi business': { icon: 'fa-briefcase', items: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Spazi all\'aperto': { icon: 'fa-tree', items: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'Servizi in camera': { icon: 'fa-concierge-bell', items: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media e tecnologia': { icon: 'fa-tv', items: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Servizi di ristorazione': { icon: 'fa-coffee', items: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', items: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parcheggio': { icon: 'fa-parking', items: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Servizi di accoglienza': { icon: 'fa-bell', items: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Intrattenimento famiglie': { icon: 'fa-child', items: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Servizi di pulizia': { icon: 'fa-broom', items: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Animali': { icon: 'fa-paw', items: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Attività': { icon: 'fa-bicycle', items: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibilità': { icon: 'fa-wheelchair', items: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Lingue parlate': { icon: 'fa-language', items: ['Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', value: 'Dalle 15:00 alle 22:30 — Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellazione', value: 'Gratuita fino a 72h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi su richiesta con supplemento di €15 al giorno' },
      { icon: 'fa-child', label: 'Bambini', value: 'Bambini dai 6 anni in su pagano tariffa adulti' },
      { icon: 'fa-credit-card', label: 'Metodi di pagamento', value: 'Mastercard, Visa, Maestro, Contanti' },
    ],
    surroundings: {
      'Ristoranti e Caffetterie': { icon: 'fa-utensils', items: ['Caffetteria/Bar Vino e Bottega — 1 km', 'Ristorante Da Maddalena — 1,2 km', 'Pasticceria Austa — 1,4 km'] },
      'Mezzi Pubblici': { icon: 'fa-train', items: ['Treno Costigliole d\'Asti — 5 km', 'Treno Vigliano d\'Asti — 7 km'] },
      'Aeroporti': { icon: 'fa-plane', items: ['Aeroporto di Cuneo - Levaldigi — 62 km', 'Aeroporto di Torino — 73 km', 'Aeroporto di Genova-Sestri — 93 km'] },
    },
    prev: 'tripla',
    next: 'family',
  },
  {
    slug: 'family',
    name: 'Camera Family',
    tagline: 'La famiglia al centro, il Piemonte tutt\'intorno',
    description: `La Camera Family è stata pensata con le famiglie nel cuore. Ogni dettaglio risponde alle esigenze dei genitori e dei bambini: spazi organizzati, arredi sicuri, dotazioni pensate per i più piccoli.

Dal fasciatoio alla culla, dal kit bambini ai giochi di benvenuto — perché anche i bambini meritano un soggiorno memorabile nelle Langhe.`,
    heroImg: '/foto/family.webp',
    gallery: [
      '/foto/family.webp',
      '/foto/family.webp',
      '/foto/family.webp',
      '/foto/family.webp',
      '/foto/family.webp',
    ],
    price: 220,
    priceNote: 'per notte (colazione esclusa)',
    specs: [
      { icon: 'fa-bed', label: 'Predisposizione letto', value: 'Su richiesta' },
      { icon: 'fa-users', label: 'Ospiti', value: '2 Adulti + 2 Bambini' },
      { icon: 'fa-glass-whiskey', label: 'Frigobar', value: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Fumo', value: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Colazione', value: 'Inclusa per tutti' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi su richiesta' },
      { icon: 'fa-door-open', label: 'Check-in', value: 'Dalle 15:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bagno': { icon: 'fa-bath', items: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'Servizi generali': { icon: 'fa-concierge-bell', items: ['Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Servizi business': { icon: 'fa-briefcase', items: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Spazi all\'aperto': { icon: 'fa-tree', items: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'Servizi in camera': { icon: 'fa-concierge-bell', items: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media e tecnologia': { icon: 'fa-tv', items: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Servizi di ristorazione': { icon: 'fa-coffee', items: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', items: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parcheggio': { icon: 'fa-parking', items: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Servizi di accoglienza': { icon: 'fa-bell', items: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Intrattenimento famiglie': { icon: 'fa-child', items: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Servizi di pulizia': { icon: 'fa-broom', items: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Animali': { icon: 'fa-paw', items: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Attività': { icon: 'fa-bicycle', items: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibilità': { icon: 'fa-wheelchair', items: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Lingue parlate': { icon: 'fa-language', items: ['Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', value: 'Dalle 15:00 alle 22:30 — Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellazione', value: 'Gratuita fino a 48h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi su richiesta con supplemento di €15 al giorno' },
      { icon: 'fa-child', label: 'Bambini', value: 'Bambini dai 6 anni in su pagano tariffa adulti' },
      { icon: 'fa-credit-card', label: 'Metodi di pagamento', value: 'Mastercard, Visa, Maestro, Contanti' },
    ],
    surroundings: {
      'Ristoranti e Caffetterie': { icon: 'fa-utensils', items: ['Caffetteria/Bar Vino e Bottega — 1 km', 'Ristorante Da Maddalena — 1,2 km', 'Pasticceria Austa — 1,4 km'] },
      'Mezzi Pubblici': { icon: 'fa-train', items: ['Treno Costigliole d\'Asti — 5 km', 'Treno Vigliano d\'Asti — 7 km'] },
      'Aeroporti': { icon: 'fa-plane', items: ['Aeroporto di Cuneo - Levaldigi — 62 km', 'Aeroporto di Torino — 73 km', 'Aeroporto di Genova-Sestri — 93 km'] },
    },
    prev: 'quadrupla',
    next: 'suite',
  },
  {
    slug: 'suite',
    name: 'Suite Deluxe',
    tagline: 'L\'apice del lusso piemontese',
    description: `La Suite Deluxe è un'esperienza a sé. Un appartamento di lusso immerso tra le colline patrimonio UNESCO, dove ogni elemento racconta la storia delle Langhe attraverso materiali pregiati e un servizio senza pari.

Soggiorno separato, terrazza panoramica privata, spa con jacuzzi, sauna e butler dedicato. Per anniversari, luna di miele e ogni momento che merita di diventare un ricordo eterno.`,
    heroImg: '/foto/suite.webp',
    gallery: [
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
    ],
    price: 140,
    priceNote: 'per notte (colazione esclusa)',
    specs: [
      { icon: 'fa-bed', label: 'Predisposizione letto', value: 'Su richiesta' },
      { icon: 'fa-users', label: 'Ospiti', value: '2 Adulti' },
      { icon: 'fa-glass-whiskey', label: 'Frigobar', value: 'In camera' },
      { icon: 'fa-spa', label: 'Spa Privata', value: 'Jacuzzi + Sauna' },
      { icon: 'fa-utensils', label: 'Cena', value: 'Gourmet Inclusa' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi su richiesta' },
      { icon: 'fa-door-open', label: 'Check-in', value: 'Dalle 15:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bagno': { icon: 'fa-bath', items: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'Servizi generali': { icon: 'fa-concierge-bell', items: ['Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Servizi business': { icon: 'fa-briefcase', items: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Spazi all\'aperto': { icon: 'fa-tree', items: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'Servizi in camera': { icon: 'fa-concierge-bell', items: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media e tecnologia': { icon: 'fa-tv', items: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Servizi di ristorazione': { icon: 'fa-coffee', items: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', items: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parcheggio': { icon: 'fa-parking', items: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Servizi di accoglienza': { icon: 'fa-bell', items: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Intrattenimento famiglie': { icon: 'fa-child', items: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Servizi di pulizia': { icon: 'fa-broom', items: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Animali': { icon: 'fa-paw', items: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Attività': { icon: 'fa-bicycle', items: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibilità': { icon: 'fa-wheelchair', items: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Lingue parlate': { icon: 'fa-language', items: ['Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', value: 'Dalle 15:00 alle 22:30 — Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellazione', value: 'Gratuita fino a 7 giorni prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi su richiesta con supplemento di €15 al giorno' },
      { icon: 'fa-child', label: 'Bambini', value: 'Bambini dai 6 anni in su pagano tariffa adulti' },
      { icon: 'fa-credit-card', label: 'Metodi di pagamento', value: 'Mastercard, Visa, Maestro, Contanti' },
    ],
    surroundings: {
      'Ristoranti e Caffetterie': { icon: 'fa-utensils', items: ['Caffetteria/Bar Vino e Bottega — 1 km', 'Ristorante Da Maddalena — 1,2 km', 'Pasticceria Austa — 1,4 km'] },
      'Mezzi Pubblici': { icon: 'fa-train', items: ['Treno Costigliole d\'Asti — 5 km', 'Treno Vigliano d\'Asti — 7 km'] },
      'Aeroporti': { icon: 'fa-plane', items: ['Aeroporto di Cuneo - Levaldigi — 62 km', 'Aeroporto di Torino — 73 km', 'Aeroporto di Genova-Sestri — 93 km'] },
    },
    prev: 'family',
    next: null,
  },
];

const matrimonialRoom = rooms.find((room) => room.slug === 'standard');

if (matrimonialRoom) {
  rooms.unshift({
    ...matrimonialRoom,
    slug: 'singola',
    name: 'Camera Singola',
    description: matrimonialRoom.description.replace('Camera Matrimoniale', 'Camera Singola'),
    price: 90,
    prev: null,
    next: 'standard',
  });
}

export function getRoomBySlug(slug) {
  return rooms.find((r) => r.slug === slug) || null;
}

export function getAllRoomSlugs() {
  return rooms.map((r) => ({ slug: r.slug }));
}
