// ================================================================
// lib/roomsData.js
// Modifica qui i dati di ogni camera (testi, foto, prezzi, servizi)
// ================================================================

export const rooms = [
  {
    slug: 'standard',
    name: 'Camera Standard',
    tagline: 'Il comfort essenziale del Piemonte autentico',
    description: `La Camera Standard è il punto di partenza perfetto per scoprire le Langhe. Arredata con cura artigianale, unisce funzionalità e calore in un ambiente accogliente che profuma di territorio.

Ogni dettaglio è pensato per farti sentire a casa: dalla biancheria pregiata ai prodotti da bagno locali, dalla vista sul giardino alla luce morbida del mattino piemontese.`,
    heroImg: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1800&q=85&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80&fit=crop',
    ],
    price: 120,
    priceNote: 'per notte, colazione inclusa',
    specs: [
      { icon: 'fa-bed', label: 'Letto', value: 'Matrimoniale' },
      { icon: 'fa-users', label: 'Ospiti', value: '2 Adulti' },
      { icon: 'fa-eye', label: 'Vista', value: 'Giardino' },
      { icon: 'fa-glass-whiskey', label: 'Frigobar', value: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Fumo', value: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Colazione', value: 'Inclusa' },
      { icon: 'fa-door-open', label: 'Check-in', value: 'Dalle 14:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bagno': { icon: 'fa-bath', items: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Pantofole', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'Servizi generali': { icon: 'fa-concierge-bell', items: ['Servizio navetta (a pagamento)', 'Ciotole per animali domestici', 'Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Ferro e asse da stiro', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Servizi business': { icon: 'fa-briefcase', items: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Spazi all\'aperto': { icon: 'fa-tree', items: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'Servizi in camera': { icon: 'fa-concierge-bell', items: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media e tecnologia': { icon: 'fa-tv', items: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Servizi di ristorazione': { icon: 'fa-coffee', items: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', items: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parcheggio': { icon: 'fa-parking', items: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Servizi di accoglienza': { icon: 'fa-bell', items: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Intrattenimento famiglie': { icon: 'fa-child', items: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Servizi di pulizia': { icon: 'fa-broom', items: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Animali': { icon: 'fa-paw', items: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Attività': { icon: 'fa-bicycle', items: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibilità': { icon: 'fa-wheelchair', items: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Lingue parlate': { icon: 'fa-language', items: ['Tedesco', 'Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', value: 'Dalle 14:00 alle 22:30 — Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellazione', value: 'Gratuita fino a 48h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Animali', value: 'Non ammessi' },
      { icon: 'fa-child', label: 'Bambini', value: 'Bambini dai 6 anni in su pagano tariffa adulti' },
    ],
    prev: null,
    next: 'tripla',
  },
  {
    slug: 'tripla',
    name: 'Camera Tripla',
    tagline: 'Spazio e stile per chi viaggia in tre',
    description: `La Camera Tripla è pensata per chi viaggia con un amico o figlio adolescente, senza dover rinunciare a nulla. Tre letti, un ambiente armonioso e tutto il comfort della tradizione piemontese.

Spaziosa e funzionale, con possibilità di configurazione flessibile, è la soluzione ideale per condividere l'esperienza delle Langhe mantenendo comfort e privacy.`,
    heroImg: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1800&q=85&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80&fit=crop',
    ],
    price: 150,
    priceNote: 'per notte, colazione inclusa',
    specs: [
      { icon: 'fa-bed', label: 'Letti', value: '1 Matrimoniale + 1 Singolo' },
      { icon: 'fa-users', label: 'Ospiti', value: '3 Adulti' },
      { icon: 'fa-eye', label: 'Vista', value: 'Vigneti' },
      { icon: 'fa-glass-whiskey', label: 'Frigobar', value: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Fumo', value: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Colazione', value: 'Inclusa' },
      { icon: 'fa-door-open', label: 'Check-in', value: 'Dalle 14:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bagno': { icon: 'fa-bath', items: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Pantofole', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'Servizi generali': { icon: 'fa-concierge-bell', items: ['Servizio navetta (a pagamento)', 'Ciotole per animali domestici', 'Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Ferro e asse da stiro', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Servizi business': { icon: 'fa-briefcase', items: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Spazi all\'aperto': { icon: 'fa-tree', items: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'Servizi in camera': { icon: 'fa-concierge-bell', items: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media e tecnologia': { icon: 'fa-tv', items: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Servizi di ristorazione': { icon: 'fa-coffee', items: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', items: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parcheggio': { icon: 'fa-parking', items: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Servizi di accoglienza': { icon: 'fa-bell', items: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Intrattenimento famiglie': { icon: 'fa-child', items: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Servizi di pulizia': { icon: 'fa-broom', items: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Animali': { icon: 'fa-paw', items: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Attività': { icon: 'fa-bicycle', items: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibilità': { icon: 'fa-wheelchair', items: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Lingue parlate': { icon: 'fa-language', items: ['Tedesco', 'Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', value: 'Dalle 14:00 alle 22:30 — Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellazione', value: 'Gratuita fino a 48h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Animali', value: 'Non ammessi' },
      { icon: 'fa-child', label: 'Bambini', value: 'Bambini dai 6 anni in su pagano tariffa adulti' },
    ],
    prev: 'standard',
    next: 'quadrupla',
  },
  {
    slug: 'quadrupla',
    name: 'Camera Quadrupla',
    tagline: 'Quattro ospiti, un\'unica esperienza indimenticabile',
    description: `La Camera Quadrupla è la scelta perfetta per gruppi di amici o famiglie che vogliono condividere gli spazi senza rinunciare al comfort individuale. Quattro posti letto in un ambiente elegante e ben organizzato.

Ideale per chi viaggia con colleghi, parenti o amici e vuole vivere le Langhe insieme, mantenendo la qualità e il calore tipici del nostro hotel.`,
    heroImg: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1800&q=85&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=900&q=80&fit=crop',
    ],
    price: 200,
    priceNote: 'per notte, colazione inclusa',
    specs: [
      { icon: 'fa-bed', label: 'Letti', value: '2 Matrimoniali' },
      { icon: 'fa-users', label: 'Ospiti', value: '4 Adulti' },
      { icon: 'fa-eye', label: 'Vista', value: 'Colline e Vigneti' },
      { icon: 'fa-glass-whiskey', label: 'Frigobar', value: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Fumo', value: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Colazione', value: 'Inclusa' },
      { icon: 'fa-door-open', label: 'Check-in', value: 'Dalle 14:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bagno': { icon: 'fa-bath', items: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Pantofole', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'Servizi generali': { icon: 'fa-concierge-bell', items: ['Servizio navetta (a pagamento)', 'Ciotole per animali domestici', 'Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Ferro e asse da stiro', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Servizi business': { icon: 'fa-briefcase', items: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Spazi all\'aperto': { icon: 'fa-tree', items: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'Servizi in camera': { icon: 'fa-concierge-bell', items: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media e tecnologia': { icon: 'fa-tv', items: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Servizi di ristorazione': { icon: 'fa-coffee', items: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', items: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parcheggio': { icon: 'fa-parking', items: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Servizi di accoglienza': { icon: 'fa-bell', items: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Intrattenimento famiglie': { icon: 'fa-child', items: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Servizi di pulizia': { icon: 'fa-broom', items: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Animali': { icon: 'fa-paw', items: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Attività': { icon: 'fa-bicycle', items: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibilità': { icon: 'fa-wheelchair', items: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Lingue parlate': { icon: 'fa-language', items: ['Tedesco', 'Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', value: 'Dalle 14:00 alle 22:30 — Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellazione', value: 'Gratuita fino a 72h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Animali', value: 'Non ammessi' },
      { icon: 'fa-child', label: 'Bambini', value: 'Bambini dai 6 anni in su pagano tariffa adulti' },
    ],
    prev: 'tripla',
    next: 'family',
  },
  {
    slug: 'family',
    name: 'Camera Family',
    tagline: 'La famiglia al centro, il Piemonte tutt\'intorno',
    description: `La Camera Family è stata pensata con le famiglie nel cuore. Ogni dettaglio risponde alle esigenze dei genitori e dei bambini: spazi organizzati, arredi sicuri, dotazioni pensate per i più piccoli.

Dal fasciatoio alla culla, dal kit bambini ai giochi di benvenuto — perché anche i bambini meritano un soggiorno memorabile nelle Langhe.`,
    heroImg: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1800&q=85&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80&fit=crop',
    ],
    price: 220,
    priceNote: 'per notte, colazione inclusa per tutti',
    specs: [
      { icon: 'fa-bed', label: 'Letti', value: '1 Matrimoniale + 2 Singoli' },
      { icon: 'fa-users', label: 'Ospiti', value: '2 Adulti + 2 Bambini' },
      { icon: 'fa-eye', label: 'Vista', value: 'Giardino e Vigneti' },
      { icon: 'fa-glass-whiskey', label: 'Frigobar', value: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Fumo', value: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Colazione', value: 'Inclusa per tutti' },
      { icon: 'fa-door-open', label: 'Check-in', value: 'Dalle 14:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bagno': { icon: 'fa-bath', items: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Pantofole', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'Servizi generali': { icon: 'fa-concierge-bell', items: ['Servizio navetta (a pagamento)', 'Ciotole per animali domestici', 'Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Ferro e asse da stiro', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Servizi business': { icon: 'fa-briefcase', items: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Spazi all\'aperto': { icon: 'fa-tree', items: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'Servizi in camera': { icon: 'fa-concierge-bell', items: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media e tecnologia': { icon: 'fa-tv', items: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Servizi di ristorazione': { icon: 'fa-coffee', items: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', items: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parcheggio': { icon: 'fa-parking', items: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Servizi di accoglienza': { icon: 'fa-bell', items: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Intrattenimento famiglie': { icon: 'fa-child', items: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Servizi di pulizia': { icon: 'fa-broom', items: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Animali': { icon: 'fa-paw', items: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Attività': { icon: 'fa-bicycle', items: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibilità': { icon: 'fa-wheelchair', items: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Lingue parlate': { icon: 'fa-language', items: ['Tedesco', 'Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', value: 'Dalle 14:00 alle 22:30 — Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellazione', value: 'Gratuita fino a 48h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Animali', value: 'Non ammessi' },
      { icon: 'fa-child', label: 'Bambini', value: 'Bambini dai 6 anni in su pagano tariffa adulti' },
    ],
    prev: 'quadrupla',
    next: 'suite',
  },
  {
    slug: 'suite',
    name: 'Suite Deluxe',
    tagline: 'L\'apice del lusso piemontese',
    description: `La Suite Deluxe è un'esperienza a sé. Un appartamento di lusso immerso tra le colline patrimonio UNESCO, dove ogni elemento racconta la storia delle Langhe attraverso materiali pregiati e un servizio senza pari.

Soggiorno separato, terrazza panoramica privata, spa con jacuzzi, sauna e butler dedicato. Per anniversari, luna di miele e ogni momento che merita di diventare un ricordo eterno.`,
    heroImg: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1800&q=85&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1455587734955-081b22074882?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=900&q=80&fit=crop',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&fit=crop',
    ],
    price: 140,
    priceNote: 'per notte — cena gourmet inclusa',
    specs: [
      { icon: 'fa-bed', label: 'Letto', value: 'King Size Premium' },
      { icon: 'fa-users', label: 'Ospiti', value: '2 Adulti' },
      { icon: 'fa-mountain', label: 'Vista', value: 'Panoramica 180° Vigneti' },
      { icon: 'fa-glass-whiskey', label: 'Frigobar', value: 'In camera' },
      { icon: 'fa-spa', label: 'Spa Privata', value: 'Jacuzzi + Sauna' },
      { icon: 'fa-utensils', label: 'Cena', value: 'Gourmet Inclusa' },
      { icon: 'fa-door-open', label: 'Check-in', value: 'Dalle 14:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bagno': { icon: 'fa-bath', items: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Pantofole', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'Servizi generali': { icon: 'fa-concierge-bell', items: ['Servizio navetta (a pagamento)', 'Ciotole per animali domestici', 'Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Ferro e asse da stiro', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Servizi business': { icon: 'fa-briefcase', items: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Spazi all\'aperto': { icon: 'fa-tree', items: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'Servizi in camera': { icon: 'fa-concierge-bell', items: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media e tecnologia': { icon: 'fa-tv', items: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Servizi di ristorazione': { icon: 'fa-coffee', items: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', items: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parcheggio': { icon: 'fa-parking', items: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Servizi di accoglienza': { icon: 'fa-bell', items: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Intrattenimento famiglie': { icon: 'fa-child', items: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Servizi di pulizia': { icon: 'fa-broom', items: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Animali': { icon: 'fa-paw', items: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Attività': { icon: 'fa-bicycle', items: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibilità': { icon: 'fa-wheelchair', items: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Lingue parlate': { icon: 'fa-language', items: ['Tedesco', 'Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', value: 'Dalle 14:00 alle 22:30 — Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', value: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellazione', value: 'Gratuita fino a 7 giorni prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Animali', value: 'Ammessi previo accordo — €30/notte' },
      { icon: 'fa-child', label: 'Bambini', value: 'Bambini dai 6 anni in su pagano tariffa adulti' },
    ],
    prev: 'family',
    next: null,
  },
];

export function getRoomBySlug(slug) {
  return rooms.find((r) => r.slug === slug) || null;
}

export function getAllRoomSlugs() {
  return rooms.map((r) => ({ slug: r.slug }));
}
