// ================================================================
// lib/roomsData.js
// Modifica qui i dati di ogni camera (testi, foto, prezzi, servizi)
// ================================================================

export const rooms = [
  {
    slug: 'standard',
    name: 'Double Room',
    name_it: 'Camera Matrimoniale',
    tagline: 'The essential comfort of authentic Piedmont',
    tagline_it: 'Il comfort essenziale del Piemonte autentico',
    description: `The Double Room is the perfect starting point to discover Langhe. Furnished with artisanal care, it combines functionality and warmth in a welcoming environment that smells of the territory.

Every detail is designed to make you feel at home: from fine linens to local bath products, from garden views to the soft light of a Piedmontese morning.`,
    description_it: `La Camera Matrimoniale è il punto di partenza perfetto per scoprire le Langhe. Arredata con cura artigianale, unisce funzionalità e calore in un ambiente accogliente che profuma di territorio.

Ogni dettaglio è pensato per farti sentire a casa: dalla biancheria pregiata ai prodotti da bagno locali, dalla vista sul giardino alla luce morbida del mattino piemontese.`,
    heroImg: '/foto/suite.webp',
    gallery: [
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
    ],
    price: 120,
    priceNote: 'per night (breakfast excluded)',
    priceNote_it: 'per notte (esclusa colazione)',
    specs: [
      { icon: 'fa-bed', label: 'Bed setup', label_it: 'Predisposizione letto', value: 'Upon request', value_it: 'Su richiesta' },
      { icon: 'fa-users', label: 'Guests', label_it: 'Ospiti', value: '2 Adults', value_it: '2 Adulti' },
      { icon: 'fa-glass-whiskey', label: 'Mini bar', label_it: 'Frigobar', value: 'In room', value_it: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Smoking', label_it: 'Fumo', value: 'Not allowed', value_it: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Breakfast', label_it: 'Colazione', value: 'Included', value_it: 'Inclusa' },
      { icon: 'fa-paw', label: 'Pets', label_it: 'Animali', value: 'Allowed upon request', value_it: 'Ammessi su richiesta' },
      { icon: 'fa-door-open', label: 'Check-in', label_it: 'Check-in', value: 'From 3:00 PM to 10:30 PM', value_it: 'Dalle 15:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', label_it: 'Check-out', value: 'From 7:00 AM to 11:00 AM', value_it: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bathroom': { icon: 'fa-bath', 
        items: ['Toilet paper', 'Towels', 'Bidet', 'Bath or shower', 'Private bathroom', 'Toilet', 'Complimentary toiletries', 'Hair dryer', 'Shower'],
        items_it: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'General Services': { icon: 'fa-concierge-bell', 
        items: ['Common area/TV lounge', 'Air conditioning', 'Non-smoking structure', 'Telephone wake-up call', 'Marble or tiled flooring', 'Heating', 'Lift', 'Family rooms available', 'Guest rooms with disabilities', 'Non-smoking rooms', 'Wake-up call/phone wake-up call'],
        items_it: ['Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Business Services': { icon: 'fa-briefcase', 
        items: ['Fax/photocopier (for a fee)', 'Business center (for a fee)', 'Meeting/banquet spaces (for a fee)'],
        items_it: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Outdoor Spaces': { icon: 'fa-tree', 
        items: ['Outdoor furniture', 'Terrace', 'Garden'],
        items_it: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'In-room Services': { icon: 'fa-concierge-bell', 
        items: ['Electrical outlet near bed', 'Coat rack'],
        items_it: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media and Technology': { icon: 'fa-tv', 
        items: ['Flat-screen TV', 'Cable channels', 'Telephone', 'TV'],
        items_it: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Food & Beverage Services': { icon: 'fa-coffee', 
        items: ['On-site cafeteria', 'Bar', 'Mini bar', 'Tea kettle/coffee machine'],
        items_it: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', 
        items: ['Free WiFi available throughout the property'],
        items_it: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parking': { icon: 'fa-parking', 
        items: ['Free private parking available on-site without reservation', 'Disabled parking'],
        items_it: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Reception Services': { icon: 'fa-bell', 
        items: ['Invoice available upon request', 'Private check-in and check-out', 'Luggage storage (for a fee)', 'Express check-in and check-out'],
        items_it: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Family Entertainment': { icon: 'fa-child', 
        items: ['Outdoor play area', 'Board games/puzzles'],
        items_it: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Cleaning Services': { icon: 'fa-broom', 
        items: ['Daily housekeeping', 'Laundry service (for a fee)'],
        items_it: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Pets': { icon: 'fa-paw', 
        items: ['Pets allowed upon request. An additional fee may apply.'],
        items_it: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Activities': { icon: 'fa-bicycle', 
        items: ['Bike rental (for a fee)', 'Bike tour (for a fee)', 'Bike excursions'],
        items_it: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibility': { icon: 'fa-wheelchair', 
        items: ['Wheelchair accessible', 'Upper floors accessible by stairs only', 'Upper floors accessible by lift', 'Entire unit located on ground floor'],
        items_it: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Languages Spoken': { icon: 'fa-language', 
        items: ['English', 'French', 'Italian'],
        items_it: ['Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', label_it: 'Check-in', value: 'From 3:00 PM to 10:30 PM. Please inform us in advance of your arrival time.', value_it: 'Dalle 15:00 alle 22:30. Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', label_it: 'Check-out', value: 'From 7:00 AM to 11:00 AM', value_it: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellation', label_it: 'Cancellazione', value: 'Free up to 48 hours before arrival', value_it: 'Gratuita fino a 48h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Pets', label_it: 'Animali', value: 'Allowed upon request with a supplement of €15 per day', value_it: 'Ammessi su richiesta con supplemento di €15 al giorno' },
      { icon: 'fa-child', label: 'Children', label_it: 'Bambini', value: 'Children aged 6 and over pay adult rates', value_it: 'Bambini dai 6 anni in su pagano tariffa adulti' },
      { icon: 'fa-credit-card', label: 'Payment Methods', label_it: 'Metodi di pagamento', value: 'Mastercard, Visa, Maestro, Cash', value_it: 'Mastercard, Visa, Maestro, Contanti' },
    ],
    surroundings: {
      'Restaurants & Cafés': { icon: 'fa-utensils', 
        items: ['Caffetteria/Bar Vino e Bottega, 1 km', 'Ristorante Da Maddalena, 1.2 km', 'Pasticceria Austa, 1.4 km'],
        items_it: ['Caffetteria/Bar Vino e Bottega, 1 km', 'Ristorante Da Maddalena, 1,2 km', 'Pasticceria Austa, 1,4 km'] },
      'Public Transportation': { icon: 'fa-train', 
        items: ['Costigliole d\'Asti Train Station — 5 km', 'Vigliano d\'Asti Train Station — 7 km'],
        items_it: ['Treno Costigliole d\'Asti — 5 km', 'Treno Vigliano d\'Asti — 7 km'] },
      'Airports': { icon: 'fa-plane', 
        items: ['Cuneo - Levaldigi Airport, 62 km', 'Turin Airport, 73 km', 'Genoa-Sestri Airport, 93 km'],
        items_it: ['Aeroporto di Cuneo - Levaldigi, 62 km', 'Aeroporto di Torino, 73 km', 'Aeroporto di Genova-Sestri, 93 km'] },
    },
    prev: 'singola',
    next: 'tripla',
  },
  {
    slug: 'tripla',
    name: 'Triple Room',
    name_it: 'Camera Tripla',
    tagline: 'Space and style for three travelers',
    tagline_it: 'Spazio e stile per chi viaggia in tre',
    description: `The Triple Room is designed for those traveling with a friend or teenage child, without having to give up anything. Three beds, a harmonious environment, and all the comfort of Piedmontese tradition.

Spacious and functional, with flexible configuration options, it is the ideal solution to share the Langhe experience while maintaining comfort and privacy.`,
    description_it: `La Camera Tripla è pensata per chi viaggia con un amico o figlio adolescente, senza dover rinunciare a nulla. Tre letti, un ambiente armonioso e tutto il comfort della tradizione piemontese.

Spaziosa e funzionale, con possibilità di configurazione flessibile, è la soluzione ideale per condividere l'esperienza delle Langhe mantenendo comfort e privacy.`,
    heroImg: '/foto/Camera-tripla.webp',
    gallery: [
      '/foto/Camera-tripla.webp',
      '/foto/Camera-tripla.webp',
      '/foto/Camera-tripla.webp',
      '/foto/Camera-tripla.webp',
      '/foto/Camera-tripla.webp',
    ],
    price: 150,
    priceNote: 'per night (breakfast excluded)',
    priceNote_it: 'per notte (esclusa colazione)',
    specs: [
      { icon: 'fa-bed', label: 'Bed setup', label_it: 'Predisposizione letto', value: 'Upon request', value_it: 'Su richiesta' },
      { icon: 'fa-users', label: 'Guests', label_it: 'Ospiti', value: '3 Adults', value_it: '3 Adulti' },
      { icon: 'fa-glass-whiskey', label: 'Mini bar', label_it: 'Frigobar', value: 'In room', value_it: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Smoking', label_it: 'Fumo', value: 'Not allowed', value_it: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Breakfast', label_it: 'Colazione', value: 'Included', value_it: 'Inclusa' },
      { icon: 'fa-paw', label: 'Pets', label_it: 'Animali', value: 'Allowed upon request', value_it: 'Ammessi su richiesta' },
      { icon: 'fa-door-open', label: 'Check-in', label_it: 'Check-in', value: 'From 3:00 PM to 10:30 PM', value_it: 'Dalle 15:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', label_it: 'Check-out', value: 'From 7:00 AM to 11:00 AM', value_it: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bathroom': { icon: 'fa-bath', 
        items: ['Toilet paper', 'Towels', 'Bidet', 'Bath or shower', 'Private bathroom', 'Toilet', 'Complimentary toiletries', 'Hair dryer', 'Shower'],
        items_it: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'General Services': { icon: 'fa-concierge-bell', 
        items: ['Common area/TV lounge', 'Air conditioning', 'Non-smoking structure', 'Telephone wake-up call', 'Marble or tiled flooring', 'Heating', 'Lift', 'Family rooms available', 'Guest rooms with disabilities', 'Non-smoking rooms', 'Wake-up call/phone wake-up call'],
        items_it: ['Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Business Services': { icon: 'fa-briefcase', 
        items: ['Fax/photocopier (for a fee)', 'Business center (for a fee)', 'Meeting/banquet spaces (for a fee)'],
        items_it: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Outdoor Spaces': { icon: 'fa-tree', 
        items: ['Outdoor furniture', 'Terrace', 'Garden'],
        items_it: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'In-room Services': { icon: 'fa-concierge-bell', 
        items: ['Electrical outlet near bed', 'Coat rack'],
        items_it: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media and Technology': { icon: 'fa-tv', 
        items: ['Flat-screen TV', 'Cable channels', 'Telephone', 'TV'],
        items_it: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Food & Beverage Services': { icon: 'fa-coffee', 
        items: ['On-site cafeteria', 'Bar', 'Mini bar', 'Tea kettle/coffee machine'],
        items_it: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', 
        items: ['Free WiFi available throughout the property'],
        items_it: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parking': { icon: 'fa-parking', 
        items: ['Free private parking available on-site without reservation', 'Disabled parking'],
        items_it: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Reception Services': { icon: 'fa-bell', 
        items: ['Invoice available upon request', 'Private check-in and check-out', 'Luggage storage (for a fee)', 'Express check-in and check-out'],
        items_it: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Family Entertainment': { icon: 'fa-child', 
        items: ['Outdoor play area', 'Board games/puzzles'],
        items_it: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Cleaning Services': { icon: 'fa-broom', 
        items: ['Daily housekeeping', 'Laundry service (for a fee)'],
        items_it: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Pets': { icon: 'fa-paw', 
        items: ['Pets allowed upon request. An additional fee may apply.'],
        items_it: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Activities': { icon: 'fa-bicycle', 
        items: ['Bike rental (for a fee)', 'Bike tour (for a fee)', 'Bike excursions'],
        items_it: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibility': { icon: 'fa-wheelchair', 
        items: ['Wheelchair accessible', 'Upper floors accessible by stairs only', 'Upper floors accessible by lift', 'Entire unit located on ground floor'],
        items_it: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Languages Spoken': { icon: 'fa-language', 
        items: ['English', 'French', 'Italian'],
        items_it: ['Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', label_it: 'Check-in', value: 'From 3:00 PM to 10:30 PM. Please inform us in advance of your arrival time.', value_it: 'Dalle 15:00 alle 22:30. Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', label_it: 'Check-out', value: 'From 7:00 AM to 11:00 AM', value_it: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellation', label_it: 'Cancellazione', value: 'Free up to 48 hours before arrival', value_it: 'Gratuita fino a 48h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Pets', label_it: 'Animali', value: 'Allowed upon request with a supplement of €15 per day', value_it: 'Ammessi su richiesta con supplemento di €15 al giorno' },
      { icon: 'fa-child', label: 'Children', label_it: 'Bambini', value: 'Children aged 6 and over pay adult rates', value_it: 'Bambini dai 6 anni in su pagano tariffa adulti' },
      { icon: 'fa-credit-card', label: 'Payment Methods', label_it: 'Metodi di pagamento', value: 'Mastercard, Visa, Maestro, Cash', value_it: 'Mastercard, Visa, Maestro, Contanti' },
    ],
    surroundings: {
      'Restaurants & Cafés': { icon: 'fa-utensils', 
        items: ['Caffetteria/Bar Vino e Bottega, 1 km', 'Ristorante Da Maddalena, 1.2 km', 'Pasticceria Austa, 1.4 km'],
        items_it: ['Caffetteria/Bar Vino e Bottega, 1 km', 'Ristorante Da Maddalena, 1,2 km', 'Pasticceria Austa, 1,4 km'] },
      'Public Transportation': { icon: 'fa-train', 
        items: ['Costigliole d\'Asti Train Station — 5 km', 'Vigliano d\'Asti Train Station — 7 km'],
        items_it: ['Treno Costigliole d\'Asti — 5 km', 'Treno Vigliano d\'Asti — 7 km'] },
      'Airports': { icon: 'fa-plane', 
        items: ['Cuneo - Levaldigi Airport, 62 km', 'Turin Airport, 73 km', 'Genoa-Sestri Airport, 93 km'],
        items_it: ['Aeroporto di Cuneo - Levaldigi, 62 km', 'Aeroporto di Torino, 73 km', 'Aeroporto di Genova-Sestri, 93 km'] },
    },
    prev: 'standard',
    next: 'quadrupla',
  },
  {
    slug: 'quadrupla',
    name: 'Quadruple Room',
    name_it: 'Camera Quadrupla',
    tagline: 'Four guests, one unforgettable experience',
    tagline_it: 'Quattro ospiti, un\'unica esperienza indimenticabile',
    description: `The Quadruple Room is the perfect choice for groups of friends or families who want to share spaces without giving up individual comfort. Four beds in an elegant and well-organized environment.

Ideal for those traveling with colleagues, relatives or friends and want to experience Langhe together, maintaining the quality and warmth typical of our hotel.`,
    description_it: `La Camera Quadrupla è la scelta perfetta per gruppi di amici o famiglie che vogliono condividere gli spazi senza rinunciare al comfort individuale. Quattro posti letto in un ambiente elegante e ben organizzato.

Ideale per chi viaggia con colleghi, parenti o amici e vuole vivere le Langhe insieme, mantenendo la qualità e il calore tipici del nostro hotel.`,
    heroImg: '/foto/quadrupla.webp',
    gallery: [
      '/foto/quadrupla.webp',
      '/foto/quadrupla.webp',
      '/foto/quadrupla.webp',
      '/foto/quadrupla.webp',
      '/foto/quadrupla.webp',
    ],
    price: 200,
    priceNote: 'per night (breakfast excluded)',
    priceNote_it: 'per notte (colazione esclusa)',
    specs: [
      { icon: 'fa-bed', label: 'Bed setup', label_it: 'Predisposizione letto', value: 'Upon request', value_it: 'Su richiesta' },
      { icon: 'fa-users', label: 'Guests', label_it: 'Ospiti', value: '4 Adults', value_it: '4 Adulti' },
      { icon: 'fa-glass-whiskey', label: 'Mini bar', label_it: 'Frigobar', value: 'In room', value_it: 'In camera' },
      { icon: 'fa-smoking-ban', label: 'Smoking', label_it: 'Fumo', value: 'Not allowed', value_it: 'Non ammesso' },
      { icon: 'fa-coffee', label: 'Breakfast', label_it: 'Colazione', value: 'Included', value_it: 'Inclusa' },
      { icon: 'fa-paw', label: 'Pets', label_it: 'Animali', value: 'Allowed upon request', value_it: 'Ammessi su richiesta' },
      { icon: 'fa-door-open', label: 'Check-in', label_it: 'Check-in', value: 'From 3:00 PM to 10:30 PM', value_it: 'Dalle 15:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', label_it: 'Check-out', value: 'From 7:00 AM to 11:00 AM', value_it: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bathroom': { icon: 'fa-bath', 
        items: ['Toilet paper', 'Towels', 'Bidet', 'Bath or shower', 'Private bathroom', 'Toilet', 'Complimentary toiletries', 'Hair dryer', 'Shower'],
        items_it: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'General Services': { icon: 'fa-concierge-bell', 
        items: ['Common area/TV lounge', 'Air conditioning', 'Non-smoking structure', 'Telephone wake-up call', 'Marble or tiled flooring', 'Heating', 'Lift', 'Family rooms available', 'Guest rooms with disabilities', 'Non-smoking rooms', 'Wake-up call/phone wake-up call'],
        items_it: ['Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Business Services': { icon: 'fa-briefcase', 
        items: ['Fax/photocopier (for a fee)', 'Business center (for a fee)', 'Meeting/banquet spaces (for a fee)'],
        items_it: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Outdoor Spaces': { icon: 'fa-tree', 
        items: ['Outdoor furniture', 'Terrace', 'Garden'],
        items_it: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'In-room Services': { icon: 'fa-concierge-bell', 
        items: ['Electrical outlet near bed', 'Coat rack'],
        items_it: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media and Technology': { icon: 'fa-tv', 
        items: ['Flat-screen TV', 'Cable channels', 'Telephone', 'TV'],
        items_it: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Food & Beverage Services': { icon: 'fa-coffee', 
        items: ['On-site cafeteria', 'Bar', 'Mini bar', 'Tea kettle/coffee machine'],
        items_it: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', 
        items: ['Free WiFi available throughout the property'],
        items_it: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parking': { icon: 'fa-parking', 
        items: ['Free private parking available on-site without reservation', 'Disabled parking'],
        items_it: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Reception Services': { icon: 'fa-bell', 
        items: ['Invoice available upon request', 'Private check-in and check-out', 'Luggage storage (for a fee)', 'Express check-in and check-out'],
        items_it: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Family Entertainment': { icon: 'fa-child', 
        items: ['Outdoor play area', 'Board games/puzzles'],
        items_it: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Cleaning Services': { icon: 'fa-broom', 
        items: ['Daily housekeeping', 'Laundry service (for a fee)'],
        items_it: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Pets': { icon: 'fa-paw', 
        items: ['Pets allowed upon request. An additional fee may apply.'],
        items_it: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Activities': { icon: 'fa-bicycle', 
        items: ['Bike rental (for a fee)', 'Bike tour (for a fee)', 'Bike excursions'],
        items_it: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibility': { icon: 'fa-wheelchair', 
        items: ['Wheelchair accessible', 'Upper floors accessible by stairs only', 'Upper floors accessible by lift', 'Entire unit located on ground floor'],
        items_it: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Languages Spoken': { icon: 'fa-language', 
        items: ['English', 'French', 'Italian'],
        items_it: ['Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', label_it: 'Check-in', value: 'From 3:00 PM to 10:30 PM. Please inform us in advance of your arrival time.', value_it: 'Dalle 15:00 alle 22:30. Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', label_it: 'Check-out', value: 'From 7:00 AM to 11:00 AM', value_it: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellation', label_it: 'Cancellazione', value: 'Free up to 72 hours before arrival', value_it: 'Gratuita fino a 72h prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Pets', label_it: 'Animali', value: 'Allowed upon request with a supplement of €15 per day', value_it: 'Ammessi su richiesta con supplemento di €15 al giorno' },
      { icon: 'fa-child', label: 'Children', label_it: 'Bambini', value: 'Children aged 6 and over pay adult rates', value_it: 'Bambini dai 6 anni in su pagano tariffa adulti' },
      { icon: 'fa-credit-card', label: 'Payment Methods', label_it: 'Metodi di pagamento', value: 'Mastercard, Visa, Maestro, Cash', value_it: 'Mastercard, Visa, Maestro, Contanti' },
    ],
    surroundings: {
      'Restaurants & Cafés': { icon: 'fa-utensils', 
        items: ['Caffetteria/Bar Vino e Bottega, 1 km', 'Ristorante Da Maddalena, 1.2 km', 'Pasticceria Austa, 1.4 km'],
        items_it: ['Caffetteria/Bar Vino e Bottega, 1 km', 'Ristorante Da Maddalena, 1,2 km', 'Pasticceria Austa, 1,4 km'] },
      'Public Transportation': { icon: 'fa-train', 
        items: ['Costigliole d\'Asti Train Station — 5 km', 'Vigliano d\'Asti Train Station — 7 km'],
        items_it: ['Treno Costigliole d\'Asti — 5 km', 'Treno Vigliano d\'Asti — 7 km'] },
      'Airports': { icon: 'fa-plane', 
        items: ['Cuneo - Levaldigi Airport, 62 km', 'Turin Airport, 73 km', 'Genoa-Sestri Airport, 93 km'],
        items_it: ['Aeroporto di Cuneo - Levaldigi, 62 km', 'Aeroporto di Torino, 73 km', 'Aeroporto di Genova-Sestri, 93 km'] },
    },
    prev: 'tripla',
    next: 'suite',
  },
  {
    slug: 'suite',
    name: 'Deluxe Suite',
    name_it: 'Suite Deluxe',
    tagline: 'The pinnacle of Piedmontese luxury',
    tagline_it: 'L\'apice del lusso piemontese',
    description: `The Deluxe Suite is an experience in itself. A luxury apartment nestled among the UNESCO heritage hills, where every element tells the story of Langhe through fine materials and unparalleled service.

Separate living area, private panoramic terrace, spa with hot tub, sauna and dedicated butler. For anniversaries, honeymoons and every moment that deserves to become an eternal memory.`,
    description_it: `La Suite Deluxe è un'esperienza a sé. Un appartamento di lusso immerso tra le colline patrimonio UNESCO, dove ogni elemento racconta la storia delle Langhe attraverso materiali pregiati e un servizio senza pari.

Soggiorno separato, terrazza panoramica privata, spa con jacuzzi, sauna e butler dedicato. Per anniversari, luna di miele e ogni momento che merita di diventare un ricordo eterno.`,
    heroImg: '/foto/suite.webp',
    gallery: [
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
      '/foto/suite.webp',
    ],
    price: 140,
    priceNote: 'per night (breakfast excluded)',
    priceNote_it: 'per notte (colazione esclusa)',
    specs: [
      { icon: 'fa-bed', label: 'Bed setup', label_it: 'Predisposizione letto', value: 'Upon request', value_it: 'Su richiesta' },
      { icon: 'fa-users', label: 'Guests', label_it: 'Ospiti', value: '2 Adults', value_it: '2 Adulti' },
      { icon: 'fa-glass-whiskey', label: 'Mini bar', label_it: 'Frigobar', value: 'In room', value_it: 'In camera' },
      { icon: 'fa-spa', label: 'Private Spa', label_it: 'Spa Privata', value: 'Hot tub + Sauna', value_it: 'Jacuzzi + Sauna' },
      { icon: 'fa-utensils', label: 'Dinner', label_it: 'Cena', value: 'Gourmet Included', value_it: 'Gourmet Inclusa' },
      { icon: 'fa-paw', label: 'Pets', label_it: 'Animali', value: 'Allowed upon request', value_it: 'Ammessi su richiesta' },
      { icon: 'fa-door-open', label: 'Check-in', label_it: 'Check-in', value: 'From 3:00 PM to 10:30 PM', value_it: 'Dalle 15:00 alle 22:30' },
      { icon: 'fa-sign-out-alt', label: 'Check-out', label_it: 'Check-out', value: 'From 7:00 AM to 11:00 AM', value_it: 'Dalle 07:00 alle 11:00' },
    ],
    amenities: {
      'Bathroom': { icon: 'fa-bath', 
        items: ['Toilet paper', 'Towels', 'Bidet', 'Bath or shower', 'Private bathroom', 'Toilet', 'Complimentary toiletries', 'Hair dryer', 'Shower'],
        items_it: ['Carta igienica', 'Asciugamani', 'Bidet', 'Vasca o doccia', 'Bagno privato', 'WC', 'Prodotti da bagno in omaggio', 'Asciugacapelli', 'Doccia'] },
      'General Services': { icon: 'fa-concierge-bell', 
        items: ['Common area/TV lounge', 'Air conditioning', 'Non-smoking structure', 'Telephone wake-up call', 'Marble or tiled flooring', 'Heating', 'Lift', 'Family rooms available', 'Guest rooms with disabilities', 'Non-smoking rooms', 'Wake-up call/phone wake-up call'],
        items_it: ['Sala comune/zona TV', 'Aria condizionata', 'Struttura interamente non fumatori', 'Sveglia telefonica', 'Pavimento in marmo o in piastrelle', 'Riscaldamento', 'Ascensore', 'Disponibilità di camere familiari', 'Camere/strutture per ospiti disabili', 'Camere non fumatori', 'Sveglia/sveglia telefonica'] },
      'Business Services': { icon: 'fa-briefcase', 
        items: ['Fax/photocopier (for a fee)', 'Business center (for a fee)', 'Meeting/banquet spaces (for a fee)'],
        items_it: ['Fax/fotocopiatrice (a pagamento)', 'Centro business (a pagamento)', 'Spazi per riunioni/banchetti (a pagamento)'] },
      'Outdoor Spaces': { icon: 'fa-tree', 
        items: ['Outdoor furniture', 'Terrace', 'Garden'],
        items_it: ['Arredamento da esterni', 'Terrazza', 'Giardino'] },
      'In-room Services': { icon: 'fa-concierge-bell', 
        items: ['Electrical outlet near bed', 'Coat rack'],
        items_it: ['Presa elettrica vicino al letto', 'Stand appendiabiti'] },
      'Media and Technology': { icon: 'fa-tv', 
        items: ['Flat-screen TV', 'Cable channels', 'Telephone', 'TV'],
        items_it: ['TV a schermo piatto', 'Canali via cavo', 'Telefono', 'TV'] },
      'Food & Beverage Services': { icon: 'fa-coffee', 
        items: ['On-site cafeteria', 'Bar', 'Mini bar', 'Tea kettle/coffee machine'],
        items_it: ['Caffetteria sul posto', 'Bar', 'Minibar', 'Bollitore tè/macchina caffè'] },
      'Internet': { icon: 'fa-wifi', 
        items: ['Free WiFi available throughout the property'],
        items_it: ['Internet WiFi disponibile gratuitamente in tutta la struttura'] },
      'Parking': { icon: 'fa-parking', 
        items: ['Free private parking available on-site without reservation', 'Disabled parking'],
        items_it: ['Parcheggio privato disponibile gratuitamente in loco senza prenotazione', 'Parcheggio per disabili'] },
      'Reception Services': { icon: 'fa-bell', 
        items: ['Invoice available upon request', 'Private check-in and check-out', 'Luggage storage (for a fee)', 'Express check-in and check-out'],
        items_it: ['Fattura disponibile su richiesta', 'Check-in e check-out privati', 'Deposito bagagli (a pagamento)', 'Check-in e check-out express'] },
      'Family Entertainment': { icon: 'fa-child', 
        items: ['Outdoor play area', 'Board games/puzzles'],
        items_it: ['Area giochi all\'aperto', 'Giochi da tavolo/puzzle'] },
      'Cleaning Services': { icon: 'fa-broom', 
        items: ['Daily housekeeping', 'Laundry service (for a fee)'],
        items_it: ['Servizio pulizie giornaliero', 'Servizio lavanderia (a pagamento)'] },
      'Pets': { icon: 'fa-paw', 
        items: ['Pets allowed upon request. An additional fee may apply.'],
        items_it: ['Animali ammessi su richiesta. Potrebbe essere richiesto un supplemento.'] },
      'Activities': { icon: 'fa-bicycle', 
        items: ['Bike rental (for a fee)', 'Bike tour (for a fee)', 'Bike excursions'],
        items_it: ['Noleggio biciclette (a pagamento)', 'Tour in bicicletta (a pagamento)', 'Escursioni in bicicletta'] },
      'Accessibility': { icon: 'fa-wheelchair', 
        items: ['Wheelchair accessible', 'Upper floors accessible by stairs only', 'Upper floors accessible by lift', 'Entire unit located on ground floor'],
        items_it: ['Accesso su sedia a rotelle', 'Piani superiori accessibili solo tramite scale', 'Piani superiori accessibili tramite ascensore', 'Intera unità situata al piano terra'] },
      'Languages Spoken': { icon: 'fa-language', 
        items: ['English', 'French', 'Italian'],
        items_it: ['Inglese', 'Francese', 'Italiano'] },
    },
    policies: [
      { icon: 'fa-calendar-check', label: 'Check-in', label_it: 'Check-in', value: 'From 3:00 PM to 10:30 PM. Please inform us in advance of your arrival time.', value_it: 'Dalle 15:00 alle 22:30. Comunicare in anticipo l\'orario di arrivo' },
      { icon: 'fa-calendar-times', label: 'Check-out', label_it: 'Check-out', value: 'From 7:00 AM to 11:00 AM', value_it: 'Dalle 07:00 alle 11:00' },
      { icon: 'fa-undo', label: 'Cancellation', label_it: 'Cancellazione', value: 'Free up to 7 days before arrival', value_it: 'Gratuita fino a 7 giorni prima dell\'arrivo' },
      { icon: 'fa-paw', label: 'Pets', label_it: 'Animali', value: 'Allowed upon request with a supplement of €15 per day', value_it: 'Ammessi su richiesta con supplemento di €15 al giorno' },
      { icon: 'fa-child', label: 'Children', label_it: 'Bambini', value: 'Children aged 6 and over pay adult rates', value_it: 'Bambini dai 6 anni in su pagano tariffa adulti' },
      { icon: 'fa-credit-card', label: 'Payment Methods', label_it: 'Metodi di pagamento', value: 'Mastercard, Visa, Maestro, Cash', value_it: 'Mastercard, Visa, Maestro, Contanti' },
    ],
    surroundings: {
      'Restaurants & Cafés': { icon: 'fa-utensils', 
        items: ['Caffetteria/Bar Vino e Bottega, 1 km', 'Ristorante Da Maddalena, 1.2 km', 'Pasticceria Austa, 1.4 km'],
        items_it: ['Caffetteria/Bar Vino e Bottega, 1 km', 'Ristorante Da Maddalena, 1,2 km', 'Pasticceria Austa, 1,4 km'] },
      'Public Transportation': { icon: 'fa-train', 
        items: ['Costigliole d\'Asti Train Station — 5 km', 'Vigliano d\'Asti Train Station — 7 km'],
        items_it: ['Treno Costigliole d\'Asti — 5 km', 'Treno Vigliano d\'Asti — 7 km'] },
      'Airports': { icon: 'fa-plane', 
        items: ['Cuneo - Levaldigi Airport, 62 km', 'Turin Airport, 73 km', 'Genoa-Sestri Airport, 93 km'],
        items_it: ['Aeroporto di Cuneo - Levaldigi, 62 km', 'Aeroporto di Torino, 73 km', 'Aeroporto di Genova-Sestri, 93 km'] },
    },
    prev: 'quadrupla',
    next: null,
  },
];

const matrimonialRoom = rooms.find((room) => room.slug === 'standard');

if (matrimonialRoom) {
  rooms.unshift({
    ...matrimonialRoom,
    slug: 'singola',
    name: 'Single Room',
    name_it: 'Camera Singola',
    description: matrimonialRoom.description.replace('The Double Room', 'The Single Room').replace('La Camera Matrimoniale', 'La Camera Singola'),
    description_it: matrimonialRoom.description_it.replace('Camera Matrimoniale', 'Camera Singola'),
    price: 90,
    prev: null,
    next: 'standard',
  });
}

export function getRoomBySlug(slug) {
  return rooms.find((r) => r.slug === slug) || null;
}

export function getAllRoomSlugs() {
  return rooms.map((r) => ({ slug: r.slug }));
}
