export const sale = [
  {
    slug: 'conference-hall-vittorio-alfieri',
    nome: 'Conference Hall Vittorio Alfieri',
    sottotitolo: 'Sala congressi multimediale con luce naturale e completamente oscurabile',
    tagline: 'La sala principale per grandi eventi aziendali e congressuali, con capienza fino a 400 posti a platea.',
    img: '/foto/hotel_langhe_sala_meeting_alfieri.webp',
    specs: [
      { icon: 'fa-users', label: 'Capienza', value: '400 posti a platea' },
      { icon: 'fa-sun', label: 'Luce', value: 'Naturale + oscurabile' },
      { icon: 'fa-desktop', label: 'Formato', value: 'Sala congressi multimediale' },
    ],
    configurazioni: [
      { tipo: 'Platea', posti: 400, icon: 'fa-users' },
    ],
    dotazioni: [
      'Tre schermi giganti motorizzati',
      'Impianto di amplificazione',
      'Radiomicrofoni',
      '3 videoproiettori fissi',
      'Palco oratori con microfoni',
      'Registrazione audio-video',
      'Laser beam',
      'Telecamera registrazione video',
      'Lavagna a fogli mobili',
      'Accesso diretto Internet ADSL',
      'Video-teleconferenza',
      'Lettore DVD e VHS',
      'Telefono diretto',
      'Sala regia',
      'Servizi fotografici su richiesta',
      'Allestimenti floreali su richiesta',
    ],
  },
  {
    slug: 'meeting-room-cesare-pavese',
    nome: 'Meeting Room Cesare Pavese',
    sottotitolo: 'Sala meeting collegabile audio-video con la Conference Hall Vittorio Alfieri',
    tagline: 'Spazio ideale per riunioni, formazione e sessioni operative, con doppia configurazione di capienza.',
    img: '/foto/hotel_langhe_sala_meeting_pavese.webp',
    specs: [
      { icon: 'fa-users', label: 'Capienza a platea', value: '70 posti' },
      { icon: 'fa-horse-head', label: 'Ferro di cavallo', value: '20 posti' },
      { icon: 'fa-link', label: 'Collegamento', value: 'Audio-video con Alfieri' },
    ],
    configurazioni: [
      { tipo: 'Platea', posti: 70, icon: 'fa-users' },
      { tipo: 'Ferro di Cavallo', posti: 20, icon: 'fa-horse-head' },
    ],
    dotazioni: [
      'Schermo gigante',
      'Impianto di amplificazione',
      'Lettore DVD e VHS',
      'Accesso Internet diretto con ADSL',
      'Videoproiettore fisso',
      'Microfoni oratori',
      'Telefono diretto',
      'Luce naturale',
    ],
  },
  {
    slug: 'meeting-room-beppe-fenoglio',
    nome: 'Meeting Room Beppe Fenoglio',
    sottotitolo: 'Sala meeting flessibile per gruppi medi e workshop operativi',
    tagline: 'Sala dedicata a meeting e formazione con doppia configurazione e possibilità di integrazione con Cesare Pavese.',
    img: '/foto/hotel_langhe_sala_meeting_fenoglio.webp',
    specs: [
      { icon: 'fa-users', label: 'Capienza a platea', value: '60 posti' },
      { icon: 'fa-horse-head', label: 'Ferro di cavallo', value: '16 posti' },
      { icon: 'fa-object-group', label: 'Combinabile', value: 'Con Meeting Room Cesare Pavese' },
    ],
    configurazioni: [
      { tipo: 'Platea', posti: 60, icon: 'fa-users' },
      { tipo: 'Ferro di Cavallo', posti: 16, icon: 'fa-horse-head' },
    ],
    dotazioni: [
      'Impianto di amplificazione',
      'Radiomicrofono',
      'Accesso Internet diretto con ADSL',
      'Microfoni oratori',
      'Telefono diretto',
    ],
    nota: 'Le due Meeting Rooms si possono collegare per ottenere una sala di 135 mq con una capienza di 130 posti a platea.',
  },
];
