export const sale = [
  {
    slug: 'conference-hall-vittorio-alfieri',
    nome: 'Conference Hall Vittorio Alfieri',
    nome_it: 'Conference Hall Vittorio Alfieri',
    sottotitolo: 'Multimedia conference hall with natural and completely blackout light',
    sottotitolo_it: 'Sala congressi multimediale con luce naturale e completamente oscurabile',
    tagline: 'The main hall for large corporate events and conferences, with capacity up to 400 seats in plenary format.',
    tagline_it: 'La sala principale per grandi eventi aziendali e congressuali, con capienza fino a 400 posti a platea.',
    img: '/foto/hotel_langhe_sala_meeting_alfieri.webp',
    specs: [
      { icon: 'fa-users', label: 'Capacity', label_it: 'Capienza', value: '400 plenary seats', value_it: '400 posti a platea' },
      { icon: 'fa-sun', label: 'Light', label_it: 'Luce', value: 'Natural + blackout', value_it: 'Naturale + oscurabile' },
      { icon: 'fa-desktop', label: 'Format', label_it: 'Formato', value: 'Multimedia conference hall', value_it: 'Sala congressi multimediale' },
    ],
    configurazioni: [
      { tipo: 'Plenary', tipo_it: 'Platea', posti: 400, icon: 'fa-users' },
    ],
    dotazioni: [
      'Three motorized giant screens',
      'Amplification system',
      'Wireless microphones',
      '3 fixed video projectors',
      'Speaker stage with microphones',
      'Audio-video recording',
      'Laser beam',
      'Video recording camera',
      'Mobile flip chart',
      'Direct Internet ADSL access',
      'Video-conferencing',
      'DVD and VHS player',
      'Direct phone',
      'Technical control room',
      'Photography services upon request',
      'Floral arrangements upon request',
    ],
    dotazioni_it: [
      'Tre schermi giganti motorizzati',
      'Impianto di amplificazione',
      'Radiomicrofoni',
      '3 videoproiettori fissi',
      'Palco oratori con microfoni',
      'Registrazione audio-video',
      'Laser beam',
      'Telecamera registrazione video',
      'Lavagna a fogli mobili',
      'Accesso diretto Internet ADSL',
      'Video-teleconferenza',
      'Lettore DVD e VHS',
      'Telefono diretto',
      'Sala regia',
      'Servizi fotografici su richiesta',
      'Allestimenti floreali su richiesta',
    ],
  },
  {
    slug: 'meeting-room-cesare-pavese',
    nome: 'Meeting Room Cesare Pavese',
    nome_it: 'Meeting Room Cesare Pavese',
    sottotitolo: 'Meeting room with audio-video connection to Conference Hall Vittorio Alfieri',
    sottotitolo_it: 'Sala meeting collegabile audio-video con la Conference Hall Vittorio Alfieri',
    tagline: 'Ideal space for meetings, training and operational sessions, with dual capacity configuration.',
    tagline_it: 'Spazio ideale per riunioni, formazione e sessioni operative, con doppia configurazione di capienza.',
    img: '/foto/hotel_langhe_sala_meeting_pavese.webp',
    specs: [
      { icon: 'fa-users', label: 'Plenary capacity', label_it: 'Capienza a platea', value: '70 seats', value_it: '70 posti' },
      { icon: 'fa-horse-head', label: 'Horseshoe', label_it: 'Ferro di cavallo', value: '20 seats', value_it: '20 posti' },
      { icon: 'fa-link', label: 'Connection', label_it: 'Collegamento', value: 'Audio-video with Alfieri', value_it: 'Audio-video con Alfieri' },
    ],
    configurazioni: [
      { tipo: 'Plenary', tipo_it: 'Platea', posti: 70, icon: 'fa-users' },
      { tipo: 'Horseshoe', tipo_it: 'Ferro di Cavallo', posti: 20, icon: 'fa-horse-head' },
    ],
    dotazioni: [
      'Giant screen',
      'Amplification system',
      'DVD and VHS player',
      'Direct Internet access with ADSL',
      'Fixed video projector',
      'Speaker microphones',
      'Direct phone',
      'Natural light',
    ],
    dotazioni_it: [
      'Schermo gigante',
      'Impianto di amplificazione',
      'Lettore DVD e VHS',
      'Accesso Internet diretto con ADSL',
      'Videoproiettore fisso',
      'Microfoni oratori',
      'Telefono diretto',
      'Luce naturale',
    ],
  },
  {
    slug: 'meeting-room-beppe-fenoglio',
    nome: 'Meeting Room Beppe Fenoglio',
    nome_it: 'Meeting Room Beppe Fenoglio',
    sottotitolo: 'Flexible meeting room for medium-sized groups and operational workshops',
    sottotitolo_it: 'Sala meeting flessibile per gruppi medi e workshop operativi',
    tagline: 'Dedicated meeting and training room with dual configuration and possibility of integration with Cesare Pavese.',
    tagline_it: 'Sala dedicata a meeting e formazione con doppia configurazione e possibilità di integrazione con Cesare Pavese.',
    img: '/foto/hotel_langhe_sala_meeting_fenoglio.webp',
    specs: [
      { icon: 'fa-users', label: 'Plenary capacity', label_it: 'Capienza a platea', value: '60 seats', value_it: '60 posti' },
      { icon: 'fa-horse-head', label: 'Horseshoe', label_it: 'Ferro di cavallo', value: '16 seats', value_it: '16 posti' },
      { icon: 'fa-object-group', label: 'Combinable', label_it: 'Combinabile', value: 'With Meeting Room Cesare Pavese', value_it: 'Con Meeting Room Cesare Pavese' },
    ],
    configurazioni: [
      { tipo: 'Plenary', tipo_it: 'Platea', posti: 60, icon: 'fa-users' },
      { tipo: 'Horseshoe', tipo_it: 'Ferro di Cavallo', posti: 16, icon: 'fa-horse-head' },
    ],
    dotazioni: [
      'Amplification system',
      'Wireless microphone',
      'Direct Internet access with ADSL',
      'Speaker microphones',
      'Direct phone',
    ],
    dotazioni_it: [
      'Impianto di amplificazione',
      'Radiomicrofono',
      'Accesso Internet diretto con ADSL',
      'Microfoni oratori',
      'Telefono diretto',
    ],
    nota: 'The two Meeting Rooms can be connected to obtain a hall of 135 sqm with a capacity of 130 seats in plenary format.',
    nota_it: 'Le due Meeting Rooms si possono collegare per ottenere una sala di 135 mq con una capienza di 130 posti a platea.',
  },
];
